
import "./globals.css"
import NavBar from "./components/nav-bar";
import Footer from "./components/footer";


export const metadata = {
  title: "Your App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        

        <NavBar />
        <main>
        {children}

        </main>         
        <Footer />
          
        
        
      </body>
    </html>
  );
}
